apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: service1-cert
  namespace: istio-ingress 
spec:
  commonName: service1.example.id
  dnsNames:
  - service1.example.id
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  renewBefore: 360h0m0s
  secretName: service1-cert

